sudo: required
services:
    - docker

before_install:
    - docker build -t rasarishi/docker-react -f Dockerfile.dev .
    
script:
    - docker run -t rasarishi/docker-react npm run test -- --coverage
    